version: '3'

services:

    mysql:
        image: '${PROJECT_NAME}/mysql'
        container_name: '${PROJECT_NAME}_mysql'
        hostname: '${MYSQL_HOST}'
        build:
            context: './mysql'
            dockerfile: 'Dockerfile'
        environment:
            - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
            - 'MYSQL_USER=${MYSQL_USERNAME}'
            - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
            - 'MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}'
        ports:
            - '${MYSQL_PORT_BINDING}:${MYSQL_PORT}'

    redis:
        image: '${PROJECT_NAME}/redis'
        container_name: '${PROJECT_NAME}_redis'
        hostname: '${REDIS_HOST}'
        build:
            context: './redis'
            dockerfile: 'Dockerfile'
        ports:
            - '${REDIS_PORT_BINDING}:${REDIS_PORT}'

    php:
        image: '${PROJECT_NAME}/php'
        container_name: '${PROJECT_NAME}_php'
        hostname: '${PHP_HOST}'
        build:
            context: './php'
            dockerfile: 'Dockerfile'
        volumes:
            - '${HOST_ROOT}/:${DOCKER_ROOT}'
        working_dir: '${DOCKER_ROOT}'
        user: '${USER}'
        env_file:
          - '${HOST_ROOT}/.env'
        environment:
            - 'PIMCORE_INSTALL_ADMIN_USERNAME=${PIMCORE_USERNAME}'
            - 'PIMCORE_INSTALL_ADMIN_PASSWORD=${PIMCORE_PASSWORD}'
            - 'PIMCORE_INSTALL_MYSQL_HOST_SOCKET=${MYSQL_HOST}'
            - 'PIMCORE_INSTALL_MYSQL_USERNAME=${MYSQL_USERNAME}'
            - 'PIMCORE_INSTALL_MYSQL_PASSWORD=${MYSQL_PASSWORD}'
            - 'PIMCORE_INSTALL_MYSQL_DATABASE=${MYSQL_DATABASE}'
            - 'PIMCORE_INSTALL_MYSQL_PORT=${MYSQL_PORT}'
        depends_on:
            - 'mysql'
            - 'redis'

    apache:
        image: '${PROJECT_NAME}/apache'
        container_name: '${PROJECT_NAME}_apache'
        hostname: '${APACHE_HOST}'
        build:
            context: './apache'
            dockerfile: 'Dockerfile'
        volumes:
            - '${HOST_ROOT}/:${DOCKER_ROOT}'
        working_dir: '${DOCUMENT_ROOT}'
        ports:
            - '${APACHE_PORT_BINDING}:${APACHE_PORT}'
        depends_on:
            - 'php'
